/************************************************************************
 *				北京科银京成技术有限公司 版权所有
 *    Copyright (C) 2000-2011 CoreTek Systems Inc. All Rights Reserved.
 ***********************************************************************/

package com.coretek.spte.testcase;

import com.coretek.common.template.build.codeTemplate.EntityRules;
import com.coretek.common.template.build.codeTemplate.FieldRules;

/**
 * 此类对应于xml上的 "description" 节点. 如果您不是专业人士，请不要修改此文件.
 * 
 * @author GENERATED BY SPTE_CODE_ROBOT
 */
@EntityRules(xpath = "description", xmlName = "description", displayField = "", dragable = false, superClazz = "com.coretek.common.template.XMLBean")
public class CaseDescription extends com.coretek.common.template.XMLBean
{
	/** */
	private static final long	serialVersionUID	= -5281608260154565122L;
	// 此属性对应于"criterion"
	@FieldRules(xmlName = "criterion", display = false, type = "String", node = true, editable = false, textNode = false)
	private String				criterion;
	// 此属性对应于"expected"
	@FieldRules(xmlName = "expected", display = false, type = "String", node = true, editable = false, textNode = false)
	private String				expected;
	// 此属性对应于"input"
	@FieldRules(xmlName = "input", display = false, type = "String", node = true, editable = false, textNode = false)
	private String				input;
	// 此属性对应于"REQ"
	@FieldRules(xmlName = "REQ", display = false, type = "String", node = true, editable = false, textNode = false)
	private String				REQ;
	// 此属性对应于"restriction"
	@FieldRules(xmlName = "restriction", display = false, type = "String", node = true, editable = false, textNode = false)
	private String				restriction;
	// 此属性对应于"condition"
	@FieldRules(xmlName = "condition", display = false, type = "String", node = true, editable = false, textNode = false)
	private String				condition;
	// 此属性对应于"procedure"
	@FieldRules(xmlName = "procedure", display = false, type = "String", node = true, editable = false, textNode = false)
	private String				procedure;

	public String getCriterion()
	{
		return this.criterion;
	}

	public void setCriterion(String criterion)
	{
		this.criterion = criterion;
	}

	public String getExpected()
	{
		return this.expected;
	}

	public void setExpected(String expected)
	{
		this.expected = expected;
	}

	public String getInput()
	{
		return this.input;
	}

	public void setInput(String input)
	{
		this.input = input;
	}

	public String getREQ()
	{
		return this.REQ;
	}

	public void setREQ(String REQ)
	{
		this.REQ = REQ;
	}

	public String getRestriction()
	{
		return this.restriction;
	}

	public void setRestriction(String restriction)
	{
		this.restriction = restriction;
	}

	public String getCondition()
	{
		return this.condition;
	}

	public void setCondition(String condition)
	{
		this.condition = condition;
	}

	public String getProcedure()
	{
		return this.procedure;
	}

	public void setProcedure(String procedure)
	{
		this.procedure = procedure;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#clone() <br/> <b>作者</b> 孙大巍 </br> <b>日期</b>
	 * 2012-4-24
	 */
	@Override
	public Object clone() throws CloneNotSupportedException
	{

		return super.clone();
	}

}