/************************************************************************
 *				北京科银京成技术有限公司 版权所有
 *    Copyright (C) 2000-2011 CoreTek Systems Inc. All Rights Reserved.
 ***********************************************************************/

package com.coretek.spte.testcase;

import com.coretek.common.template.build.codeTemplate.EntityRules;
import com.coretek.common.template.build.codeTemplate.FieldRules;

/**
 * 此类对应于xml上的 "criterion" 节点. 如果您不是专业人士，请不要修改此文件.
 * 
 * @author GENERATED BY SPTE_CODE_ROBOT
 */
@EntityRules(xpath = "criterion", xmlName = "criterion", displayField = "", dragable = false, superClazz = "com.coretek.common.template.XMLBean")
public class Criterion extends com.coretek.common.template.XMLBean
{
	/** */
	private static final long	serialVersionUID	= -1338876079883356899L;
	// 此属性对应于"unexpected"
	@FieldRules(xmlName = "unexpected", display = false, type = "String", node = true, editable = false, textNode = false)
	private String				unexpected;

	public String getUnexpected()
	{
		return this.unexpected;
	}

	public void setUnexpected(String unexpected)
	{
		this.unexpected = unexpected;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#clone() <br/> <b>作者</b> 孙大巍 </br> <b>日期</b>
	 * 2012-4-24
	 */
	@Override
	public Object clone() throws CloneNotSupportedException
	{

		return super.clone();
	}

}