/************************************************************************
 *				北京科银京成技术有限公司 版权所有
 *    Copyright (C) 2000-2011 CoreTek Systems Inc. All Rights Reserved.
 ***********************************************************************/

package com.coretek.spte.testcase;

import com.coretek.common.template.build.codeTemplate.EntityRules;
import com.coretek.common.template.build.codeTemplate.FieldRules;

/**
 * 此类对应于xml上的 "ICD" 节点. 如果您不是专业人士，请不要修改此文件.
 * 
 * @author GENERATED BY SPTE_CODE_ROBOT
 */
@EntityRules(xpath = "ICD", xmlName = "ICD", displayField = "", dragable = false, superClazz = "com.coretek.common.template.XMLBean")
public class ICDFile extends com.coretek.common.template.XMLBean
{
	/** */
	private static final long	serialVersionUID	= 8734432217106112463L;
	// 此属性对应于"file"
	@FieldRules(xmlName = "file", display = false, type = "String", node = true, editable = false, textNode = false)
	private String				file;
	// 此属性对应于"version"
	@FieldRules(xmlName = "version", display = false, type = "String", node = true, editable = false, textNode = false)
	private String				version;

	// 此属性对应于"md5"
	@FieldRules(xmlName = "md5", display = false, type = "String", node = true, editable = false, textNode = false)
	private String				MD5;

	public String getMD5()
	{
		return this.MD5;
	}

	public void setMD5(String MD5)
	{
		this.MD5 = MD5;
	}

	public String getFile()
	{
		return this.file;
	}

	public void setFile(String file)
	{
		this.file = file;
	}

	public String getVersion()
	{
		return this.version;
	}

	public void setVersion(String version)
	{
		this.version = version;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#clone() <br/> <b>作者</b> 孙大巍 </br> <b>日期</b>
	 * 2012-4-24
	 */
	@Override
	public Object clone() throws CloneNotSupportedException
	{

		return super.clone();
	}

}