/************************************************************************
 *				北京科银京成技术有限公司 版权所有
 *    Copyright (C) 2000-2011 CoreTek Systems Inc. All Rights Reserved.
 ***********************************************************************/

package com.coretek.spte.testcase;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import com.coretek.common.template.build.codeTemplate.Entity;
import com.coretek.common.template.build.codeTemplate.EntityRules;
import com.coretek.common.template.build.codeTemplate.FieldRules;

/**
 * 此类对应于xml上的 "period" 节点. 如果您不是专业人士，请不要修改此文件.
 * 
 * @author GENERATED BY SPTE_CODE_ROBOT
 */
@EntityRules(xpath = "period", xmlName = "period", displayField = "", dragable = false, superClazz = "com.coretek.common.template.XMLBean")
public class Period extends com.coretek.common.template.XMLBean implements Serializable, Cloneable
{

	private static final long	serialVersionUID	= -5936477224481374213L;
	// 此属性对应于"value"
	@FieldRules(xmlName = "value", display = false, type = "Integer", node = false, editable = false, textNode = false)
	private Integer				value;

	public Integer getValue()
	{
		return this.value;
	}

	public void setValue(Integer value)
	{
		this.value = value;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#clone() <br/> <b>作者</b> 孙大巍 </br> <b>日期</b>
	 * 2012-1-10
	 */
	@Override
	public Object clone() throws CloneNotSupportedException
	{
		Period cloned = (Period) super.clone();
		List<Entity> children = this.getChildren();
		cloned.setChildren(new ArrayList<Entity>());
		List<Entity> clonedChildren = new ArrayList<Entity>(children.size());
		cloned.setParent(null);
		for (Entity child : children)
		{
			Field field = (Field) child;
			Field clonedField = (Field) field.clone();
			clonedField.setXmlName(field.getXmlName());
			clonedField.setXpath(field.getXpath());
			clonedChildren.add(clonedField);

		}
		for (Entity entity : clonedChildren)
		{
			entity.setParent(cloned);
		}
		cloned.setChildren(clonedChildren);

		return cloned;
	}
}