/************************************************************************
 *				北京科银京成技术有限公司 版权所有
 *    Copyright (C) 2000-2011 CoreTek Systems Inc. All Rights Reserved.
 ***********************************************************************/

package com.coretek.spte.testcase;

import com.coretek.common.template.build.codeTemplate.EntityRules;
import com.coretek.common.template.build.codeTemplate.FieldRules;

/**
 * 此类对应于xml上的 "refcase" 节点. 如果您不是专业人士，请不要修改此文件.
 * 
 * @author GENERATED BY SPTE_CODE_ROBOT
 */
@EntityRules(xpath = "refcase", xmlName = "refcase", displayField = "", dragable = false, superClazz = "com.coretek.common.template.XMLBean")
public class RefCase extends com.coretek.common.template.XMLBean
{
	/** */
	private static final long	serialVersionUID	= 7359288957385196965L;
	// 此属性对应于"ref"
	@FieldRules(xmlName = "ref", display = false, type = "String", node = false, editable = false, textNode = false)
	private String				value;
	// 此属性对应于"uuid"
	@FieldRules(xmlName = "uuid", display = false, type = "String", node = false, editable = false, textNode = false)
	private String				uuid;

	public String getValue()
	{
		return this.value;
	}

	public void setValue(String value)
	{
		this.value = value;
	}

	public String getUuid()
	{
		return this.uuid;
	}

	public void setUuid(String uuid)
	{
		this.uuid = uuid;
	}
}
