/************************************************************************
 *				北京科银京成技术有限公司 版权所有
 *    Copyright (C) 2000-2011 CoreTek Systems Inc. All Rights Reserved.
 ***********************************************************************/

package com.coretek.spte.testcase;

import java.util.ArrayList;
import java.util.List;

import com.coretek.common.template.build.codeTemplate.Entity;
import com.coretek.common.template.build.codeTemplate.EntityRules;
import com.coretek.common.template.build.codeTemplate.FieldRules;

/**
 * 此类对应于xml上的 "testObjects" 节点. 如果您不是专业人士，请不要修改此文件.
 * 
 * @author GENERATED BY SPTE_CODE_ROBOT
 */
@EntityRules(xpath = "testObjects", xmlName = "testObjects", displayField = "", dragable = false, superClazz = "com.coretek.common.template.XMLBean")
public class TestedObjects extends com.coretek.common.template.XMLBean
{
	/** */
	private static final long	serialVersionUID	= 6205337069536860200L;
	// 此属性对应于"level"
	@FieldRules(xmlName = "level", display = false, type = "String", node = false, editable = false, textNode = false)
	private String				level;

	public String getLevel()
	{
		return this.level;
	}

	public void setLevel(String level)
	{
		this.level = level;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#clone() <br/> <b>作者</b> 孙大巍 </br> <b>日期</b>
	 * 2012-4-24
	 */
	@Override
	public Object clone() throws CloneNotSupportedException
	{
		List<Entity> dest = new ArrayList<Entity>(this.getChildren().size());
		for (Entity entity : this.getChildren())
		{
			TestedObject to = (TestedObject) entity;
			TestedObject clonedTO = (TestedObject) to.clone();
			dest.add(clonedTO);
		}
		TestedObjects objects = (TestedObjects) super.clone();
		objects.setChildren(dest);
		return objects;
	}

}
