/************************************************************************
 *				北京科银京成技术有限公司 版权所有
 *    Copyright (C) 2000-2011 CoreTek Systems Inc. All Rights Reserved.
 ***********************************************************************/

package com.coretek.spte.unit;

import java.util.List;
import com.coretek.common.template.build.codeTemplate.Entity;
import com.coretek.common.template.build.codeTemplate.EntityRules;
import com.coretek.common.template.build.codeTemplate.FieldRules;
import com.coretek.common.template.build.codeTemplate.ReferenceRules;

/**
 * 此类对应于xml上的 "单位类型" 节点. 如果您不是专业人士，请不要修改此文件.
 * 
 * @author GENERATED BY SPTE_CODE_ROBOT
 */
@EntityRules(xpath = "单位类型", xmlName = "单位类型", displayField = "null", dragable = false)
public class UnitType extends Entity
{
	// 此属性对应于"ID"
	@FieldRules(xmlName = "ID", display = false, type = "Integer", node = false, editable = false)
	private Integer	ID;

	public Integer getID()
	{
		return this.ID;
	}

	public void setID(Integer ID)
	{
		this.ID = ID;
	}

	public String toString()
	{
		String str = "";
		str = str + "ID=" + this.ID + "\n; ";
		return str;
	}
}
