/************************************************************************
 *				北京科银京成技术有限公司 版权所有
 *    Copyright (C) 2000-2011 CoreTek Systems Inc. All Rights Reserved.
 ***********************************************************************/

package com.coretek.spte.unit;

import java.util.List;
import com.coretek.common.template.build.codeTemplate.Entity;
import com.coretek.common.template.build.codeTemplate.EntityRules;
import com.coretek.common.template.build.codeTemplate.FieldRules;
import com.coretek.common.template.build.codeTemplate.ReferenceRules;

/**
 * 此类对应于xml上的 "单位" 节点. 如果您不是专业人士，请不要修改此文件.
 * 
 * @author GENERATED BY SPTE_CODE_ROBOT
 */
@EntityRules(xpath = "单位", xmlName = "单位", displayField = "null", dragable = false)
public class Unit extends Entity
{
	// 此属性对应于"名称"
	@FieldRules(xmlName = "名称", display = false, type = "String", node = true, editable = false)
	private String	name;
	// 此属性对应于"ID"
	@FieldRules(xmlName = "ID", display = false, type = "Integer", node = true, editable = false)
	private Integer	ID;
	// 此属性对应于"显示名称"
	@FieldRules(xmlName = "显示名称", display = false, type = "String", node = true, editable = false)
	private String	displayName;

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public Integer getID()
	{
		return this.ID;
	}

	public void setID(Integer ID)
	{
		this.ID = ID;
	}

	public String getDisplayName()
	{
		return this.displayName;
	}

	public void setDisplayName(String displayName)
	{
		this.displayName = displayName;
	}

	public String toString()
	{
		String str = "";
		str = str + "name=" + this.name + "\n; ";
		str = str + "ID=" + this.ID + "\n; ";
		str = str + "displayName=" + this.displayName + "\n; ";
		return str;
	}
}
