/************************************************************************
 *				北京科银京成技术有限公司 版权所有
 *    Copyright (C) 2000-2011 CoreTek Systems Inc. All Rights Reserved.
 ***********************************************************************/

package com.coretek.spte;

import java.util.List;
import com.coretek.common.template.build.codeTemplate.Entity;
import com.coretek.common.template.build.codeTemplate.EntityRules;
import com.coretek.common.template.build.codeTemplate.FieldRules;
import com.coretek.common.template.build.codeTemplate.ReferenceRules;

/**
 * 此类对应于xml上的 "信号" 节点. 如果您不是专业人士，请不要修改此文件.
 * 
 * @author GENERATED BY SPTE_CODE_ROBOT
 */
@EntityRules(xpath = "信号", xmlName = "信号", displayField = "signalName", dragable = false, superClazz = "com.coretek.common.template.build.codeTemplate.Entity")
public class ContainedSignal extends com.coretek.common.template.build.codeTemplate.Entity
{
	// 此属性对应于"起始位"
	@FieldRules(xmlName = "起始位", display = true, type = "Integer", node = true, editable = false, textNode = false)
	private Integer					startBit;
	// 此属性对应于"起始字"
	@FieldRules(xmlName = "起始字", display = true, type = "Integer", node = true, editable = false, textNode = false)
	private Integer					startWord;
	// 此属性对应于"信号标识符"
	@FieldRules(xmlName = "信号标识符", display = true, type = "String", node = true, editable = false, textNode = false)
	private String					signalSymbol;
	// 此属性对应于"信号名称"
	@FieldRules(xmlName = "信号名称", display = true, type = "String", node = true, editable = false, textNode = false)
	private String					signalName;
	// 此属性对应于"MSB"
	@FieldRules(xmlName = "MSB", display = true, type = "String", node = true, editable = false, textNode = false)
	private String					MSB;
	// 此属性对应于"LSB"
	@FieldRules(xmlName = "LSB", display = true, type = "String", node = true, editable = false, textNode = false)
	private String					LSB;
	// 此属性对应于"单位代码"
	@FieldRules(xmlName = "单位代码", display = true, type = "String", node = true, editable = false, textNode = false)
	private String					unitCode;
	// 此属性对应于"信号组标志"
	@FieldRules(xmlName = "信号组标志", display = true, type = "Integer", node = true, editable = false, textNode = false)
	private Integer					signalGroupSymbol;
	// 引用属性
	@ReferenceRules(condition = "signalSymbol=signalSymbol", type = "com.coretek.spte.Signal")
	private com.coretek.spte.Signal	signal;

	public Integer getStartBit()
	{
		return this.startBit;
	}

	public void setStartBit(Integer startBit)
	{
		this.startBit = startBit;
	}

	public Integer getStartWord()
	{
		return this.startWord;
	}

	public void setStartWord(Integer startWord)
	{
		this.startWord = startWord;
	}

	public String getSignalSymbol()
	{
		return this.signalSymbol;
	}

	public void setSignalSymbol(String signalSymbol)
	{
		this.signalSymbol = signalSymbol;
	}

	public String getSignalName()
	{
		return this.signalName;
	}

	public void setSignalName(String signalName)
	{
		this.signalName = signalName;
	}

	public String getMSB()
	{
		return this.MSB;
	}

	public void setMSB(String MSB)
	{
		this.MSB = MSB;
	}

	public String getLSB()
	{
		return this.LSB;
	}

	public void setLSB(String LSB)
	{
		this.LSB = LSB;
	}

	public String getUnitCode()
	{
		return this.unitCode;
	}

	public void setUnitCode(String unitCode)
	{
		this.unitCode = unitCode;
	}

	public Integer getSignalGroupSymbol()
	{
		return this.signalGroupSymbol;
	}

	public void setSignalGroupSymbol(Integer signalGroupSymbol)
	{
		this.signalGroupSymbol = signalGroupSymbol;
	}

	public com.coretek.spte.Signal getSignal()
	{
		return this.signal;
	}

	public void setSignal(com.coretek.spte.Signal signal)
	{
		this.signal = signal;
	}
}
