/************************************************************************
 *				北京科银京成技术有限公司 版权所有
 *    Copyright (C) 2000-2011 CoreTek Systems Inc. All Rights Reserved.
 ***********************************************************************/

package com.coretek.spte;

import java.util.List;
import com.coretek.common.template.build.codeTemplate.Entity;
import com.coretek.common.template.build.codeTemplate.EntityRules;
import com.coretek.common.template.build.codeTemplate.FieldRules;
import com.coretek.common.template.build.codeTemplate.ReferenceRules;

/**
 * 此类对应于xml上的 "枚举" 节点. 如果您不是专业人士，请不要修改此文件.
 * 
 * @author GENERATED BY SPTE_CODE_ROBOT
 */
@EntityRules(xpath = "枚举", xmlName = "枚举", displayField = "", dragable = false, superClazz = "com.coretek.common.template.build.codeTemplate.Entity")
public class EnumBean extends com.coretek.common.template.build.codeTemplate.Entity
{
	// 此属性对应于"标识符"
	@FieldRules(xmlName = "标识符", display = false, type = "String", node = false, editable = false, textNode = false)
	private String	symbol;
	// 此属性对应于"值"
	@FieldRules(xmlName = "值", display = false, type = "Integer", node = false, editable = false, textNode = false)
	private Integer	value;

	public String getSymbol()
	{
		return this.symbol;
	}

	public void setSymbol(String symbol)
	{
		this.symbol = symbol;
	}

	public Integer getValue()
	{
		return this.value;
	}

	public void setValue(Integer value)
	{
		this.value = value;
	}
}
