/************************************************************************
 *				北京科银京成技术有限公司 版权所有
 *    Copyright (C) 2000-2011 CoreTek Systems Inc. All Rights Reserved.
 ***********************************************************************/

package com.coretek.spte;

import java.util.List;
import com.coretek.common.template.build.codeTemplate.Entity;
import com.coretek.common.template.build.codeTemplate.EntityRules;
import com.coretek.common.template.build.codeTemplate.FieldRules;
import com.coretek.common.template.build.codeTemplate.ReferenceRules;

/**
 * 此类对应于xml上的 "功能节点" 节点. 如果您不是专业人士，请不要修改此文件.
 * 
 * @author GENERATED BY SPTE_CODE_ROBOT
 */
@EntityRules(xpath = "功能节点", xmlName = "功能节点", displayField = "name", dragable = false, superClazz = "com.coretek.common.template.build.codeTemplate.Entity")
public class FunctionNode extends com.coretek.common.template.build.codeTemplate.Entity
{
	// 此属性对应于"归属上级通信对象ID"
	@FieldRules(xmlName = "归属上级通信对象ID", display = false, type = "Integer", node = true, editable = false, textNode = false)
	private Integer								parentID;
	// 此属性对应于"归属上级通信对象标识符"
	@FieldRules(xmlName = "归属上级通信对象标识符", display = false, type = "String", node = true, editable = false, textNode = false)
	private String								parentSymbol;
	// 此属性对应于"名称"
	@FieldRules(xmlName = "名称", display = true, type = "String", node = true, editable = false, textNode = false)
	private String								name;
	// 此属性对应于"ID"
	@FieldRules(xmlName = "ID", display = true, type = "Integer", node = true, editable = false, textNode = false)
	private Integer								ID;
	// 此属性对应于"缩略名"
	@FieldRules(xmlName = "缩略名", display = true, type = "String", node = true, editable = false, textNode = false)
	private String								abbreviation;
	// 引用属性
	@ReferenceRules(condition = "parentID=ID", type = "com.coretek.spte.FunctionSubDomain")
	private com.coretek.spte.FunctionSubDomain	logicParent;

	public Integer getParentID()
	{
		return this.parentID;
	}

	public void setParentID(Integer parentID)
	{
		this.parentID = parentID;
	}

	public String getParentSymbol()
	{
		return this.parentSymbol;
	}

	public void setParentSymbol(String parentSymbol)
	{
		this.parentSymbol = parentSymbol;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public Integer getID()
	{
		return this.ID;
	}

	public void setID(Integer ID)
	{
		this.ID = ID;
	}

	public String getAbbreviation()
	{
		return this.abbreviation;
	}

	public void setAbbreviation(String abbreviation)
	{
		this.abbreviation = abbreviation;
	}

	public com.coretek.spte.FunctionSubDomain getLogicParent()
	{
		return this.logicParent;
	}

	public void setLogicParent(com.coretek.spte.FunctionSubDomain logicParent)
	{
		super.setLogicParent(logicParent);
		this.logicParent = logicParent;
	}
}
