/************************************************************************
 *				北京科银京成技术有限公司 版权所有
 *    Copyright (C) 2000-2011 CoreTek Systems Inc. All Rights Reserved.
 ***********************************************************************/

package com.coretek.spte;

import java.util.List;
import com.coretek.common.template.build.codeTemplate.Entity;
import com.coretek.common.template.build.codeTemplate.EntityRules;
import com.coretek.common.template.build.codeTemplate.FieldRules;
import com.coretek.common.template.build.codeTemplate.ReferenceRules;

/**
 * 此类对应于xml上的 "功能域" 节点. 如果您不是专业人士，请不要修改此文件.
 * 
 * @author GENERATED BY SPTE_CODE_ROBOT
 */
@EntityRules(xpath = "功能域", xmlName = "功能域", displayField = "name", dragable = false, superClazz = "com.coretek.common.template.build.codeTemplate.Entity")
public class FunctionDomain extends com.coretek.common.template.build.codeTemplate.Entity
{
	// 此属性对应于"名称"
	@FieldRules(xmlName = "名称", display = false, type = "String", node = true, editable = false, textNode = false)
	private String	name;
	// 此属性对应于"ID"
	@FieldRules(xmlName = "ID", display = false, type = "Integer", node = true, editable = false, textNode = false)
	private Integer	ID;
	// 此属性对应于"缩略名"
	@FieldRules(xmlName = "缩略名", display = false, type = "String", node = true, editable = false, textNode = false)
	private String	abbreviation;

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public Integer getID()
	{
		return this.ID;
	}

	public void setID(Integer ID)
	{
		this.ID = ID;
	}

	public String getAbbreviation()
	{
		return this.abbreviation;
	}

	public void setAbbreviation(String abbreviation)
	{
		this.abbreviation = abbreviation;
	}
}
