/************************************************************************
 *				北京科银京成技术有限公司 版权所有
 *    Copyright (C) 2000-2011 CoreTek Systems Inc. All Rights Reserved.
 ***********************************************************************/

package com.coretek.spte;

import java.util.List;
import com.coretek.common.template.build.codeTemplate.Entity;
import com.coretek.common.template.build.codeTemplate.EntityRules;
import com.coretek.common.template.build.codeTemplate.FieldRules;
import com.coretek.common.template.build.codeTemplate.ReferenceRules;

/**
 * 此类对应于xml上的 "层级信息" 节点. 如果您不是专业人士，请不要修改此文件.
 * 
 * @author GENERATED BY SPTE_CODE_ROBOT
 */
@EntityRules(xpath = "层级信息", xmlName = "层级信息", displayField = "", dragable = false, superClazz = "com.coretek.common.template.build.codeTemplate.Entity")
public class LayerInfo extends com.coretek.common.template.build.codeTemplate.Entity
{
	// 此属性对应于"层级"
	@FieldRules(xmlName = "层级", display = false, type = "Integer", node = true, editable = false, textNode = false)
	private Integer	layer;
	// 此属性对应于"层级编码"
	@FieldRules(xmlName = "层级编码", display = false, type = "String", node = true, editable = false, textNode = false)
	private String	layerCode;
	// 此属性对应于"层级名称"
	@FieldRules(xmlName = "层级名称", display = false, type = "String", node = true, editable = false, textNode = false)
	private String	layerName;
	// 此属性对应于"消息属性"
	@FieldRules(xmlName = "消息属性", display = false, type = "String", node = true, editable = false, textNode = false)
	private String	msgProperty;
	// 此属性对应于"父级名称"
	@FieldRules(xmlName = "父级名称", display = false, type = "String", node = true, editable = false, textNode = false)
	private String	parentName;

	public Integer getLayer()
	{
		return this.layer;
	}

	public void setLayer(Integer layer)
	{
		this.layer = layer;
	}

	public String getLayerCode()
	{
		return this.layerCode;
	}

	public void setLayerCode(String layerCode)
	{
		this.layerCode = layerCode;
	}

	public String getLayerName()
	{
		return this.layerName;
	}

	public void setLayerName(String layerName)
	{
		this.layerName = layerName;
	}

	public String getMsgProperty()
	{
		return this.msgProperty;
	}

	public void setMsgProperty(String msgProperty)
	{
		this.msgProperty = msgProperty;
	}

	public String getParentName()
	{
		return this.parentName;
	}

	public void setParentName(String parentName)
	{
		this.parentName = parentName;
	}
}
