/************************************************************************
 *				北京科银京成技术有限公司 版权所有
 *    Copyright (C) 2000-2011 CoreTek Systems Inc. All Rights Reserved.
 ***********************************************************************/

package com.coretek.spte;

import java.util.List;
import com.coretek.common.template.build.codeTemplate.Entity;
import com.coretek.common.template.build.codeTemplate.EntityRules;
import com.coretek.common.template.build.codeTemplate.FieldRules;
import com.coretek.common.template.build.codeTemplate.ReferenceRules;

/**
 * 此类对应于xml上的 "主题" 节点. 如果您不是专业人士，请不要修改此文件.
 * 
 * @author GENERATED BY SPTE_CODE_ROBOT
 */
@EntityRules(xpath = "主题", xmlName = "主题", displayField = "topicName", dragable = false, superClazz = "com.coretek.common.template.build.codeTemplate.Entity")
public class Topic extends com.coretek.common.template.build.codeTemplate.Entity
{
	// 此属性对应于"格式类型"
	@FieldRules(xmlName = "格式类型", display = true, type = "String", node = true, editable = false, textNode = false)
	private String	formatType;
	// 此属性对应于"主题类型"
	@FieldRules(xmlName = "主题类型", display = true, type = "String", node = true, editable = false, textNode = false)
	private String	topicType;
	// 此属性对应于"主题描述"
	@FieldRules(xmlName = "主题描述", display = true, type = "String", node = true, editable = false, textNode = false)
	private String	topicDescription;
	// 此属性对应于"主题ID"
	@FieldRules(xmlName = "主题ID", display = true, type = "Integer", node = true, editable = false, textNode = false)
	private Integer	topicID;
	// 此属性对应于"主题标识符"
	@FieldRules(xmlName = "主题标识符", display = true, type = "String", node = true, editable = false, textNode = false)
	private String	topicSymbol;
	// 此属性对应于"数据长度"
	@FieldRules(xmlName = "数据长度", display = true, type = "Integer", node = true, editable = false, textNode = false)
	private Integer	dataLength;
	// 此属性对应于"主题名称"
	@FieldRules(xmlName = "主题名称", display = true, type = "String", node = true, editable = false, textNode = false)
	private String	topicName;

	public String getFormatType()
	{
		return this.formatType;
	}

	public void setFormatType(String formatType)
	{
		this.formatType = formatType;
	}

	public String getTopicType()
	{
		return this.topicType;
	}

	public void setTopicType(String topicType)
	{
		this.topicType = topicType;
	}

	public String getTopicDescription()
	{
		return this.topicDescription;
	}

	public void setTopicDescription(String topicDescription)
	{
		this.topicDescription = topicDescription;
	}

	public Integer getTopicID()
	{
		return this.topicID;
	}

	public void setTopicID(Integer topicID)
	{
		this.topicID = topicID;
	}

	public String getTopicSymbol()
	{
		return this.topicSymbol;
	}

	public void setTopicSymbol(String topicSymbol)
	{
		this.topicSymbol = topicSymbol;
	}

	public Integer getDataLength()
	{
		return this.dataLength;
	}

	public void setDataLength(Integer dataLength)
	{
		this.dataLength = dataLength;
	}

	public String getTopicName()
	{
		return this.topicName;
	}

	public void setTopicName(String topicName)
	{
		this.topicName = topicName;
	}
}
