/************************************************************************
 *				北京科银京成技术有限公司 版权所有
 *    Copyright (C) 2000-2011 CoreTek Systems Inc. All Rights Reserved.
 ***********************************************************************/

package com.coretek.spte;

import java.util.List;
import com.coretek.common.template.build.codeTemplate.Entity;
import com.coretek.common.template.build.codeTemplate.EntityRules;
import com.coretek.common.template.build.codeTemplate.FieldRules;
import com.coretek.common.template.build.codeTemplate.ReferenceRules;

/**
 * 此类对应于xml上的 "版本" 节点. 如果您不是专业人士，请不要修改此文件.
 * 
 * @author GENERATED BY SPTE_CODE_ROBOT
 */
@EntityRules(xpath = "版本", xmlName = "版本", displayField = "versionName", dragable = false, superClazz = "com.coretek.common.template.build.codeTemplate.Entity")
public class Version extends com.coretek.common.template.build.codeTemplate.Entity
{
	// 此属性对应于"版本描述"
	@FieldRules(xmlName = "版本描述", display = false, type = "String", node = true, editable = false, textNode = false)
	private String	versionDescription;
	// 此属性对应于"版本编号"
	@FieldRules(xmlName = "版本编号", display = false, type = "String", node = true, editable = false, textNode = false)
	private String	versionCode;
	// 此属性对应于"版本名称"
	@FieldRules(xmlName = "版本名称", display = false, type = "String", node = true, editable = false, textNode = false)
	private String	versionName;

	public String getVersionDescription()
	{
		return this.versionDescription;
	}

	public void setVersionDescription(String versionDescription)
	{
		this.versionDescription = versionDescription;
	}

	public String getVersionCode()
	{
		return this.versionCode;
	}

	public void setVersionCode(String versionCode)
	{
		this.versionCode = versionCode;
	}

	public String getVersionName()
	{
		return this.versionName;
	}

	public void setVersionName(String versionName)
	{
		this.versionName = versionName;
	}
}
